version: 0.{build}

branches:
  except:
    - gh-pages
    - docs

image: macos-monterey

clone_depth: 3

environment:
  global:
    GITHUB: choon
  matrix:
    - configuration: Debug
    - image: Visual Studio 2022
      configuration: Debug

install:
  - >-
    if [ $(CI_MACOS) ]; then;
      xcodebuild -version
    fi

before_build:
  - ps: $PSVersionTable

build_script:
  - ps: Get-Location
